@baseUrl = http://127.0.0.1:9400

### Ping
GET {{baseUrl}}/ping

### check
GET {{baseUrl}}/check

# 这里只是展示es推荐搜索语法 其他的请使用es原生查询语句

### 1 查询pr最大最小值
POST {{baseUrl}}/search_test/all/_search

{
  "size": 0,
  "from": 0,
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "default_field": "key",
            "query": "安阳 ",
            "minimum_should_match": "50%"
          }
        }
      ]
    }
  },
  "aggs": {
    "show_pr_min": {
      "min": {
        "field": "show_pr"
      }
    }
  }
}

### return data

#{
#  "took": 6,
#  "timed_out": false,
#  "_shards": {
#    "total": 1,
#    "successful": 1,
#    "skipped": 0,
#    "failed": 0
#  },
#  "hits": {
#    "total": 6560,
#    "max_score": 0.0,
#    "hits": []
#  },
#  "aggregations": {
#    "show_pr_max": {
#      "value": 0.0
#    },
#    "show_pr_min": {
#      "value": 0.0
#    }
#  }
#}

###

# 2 将第一步查询中的max min作为第二次查询的参数 搜索条件与上次相同
POST {{baseUrl}}/search_test/all/_search
Content-Type: application/json

{
  "_source": [
    "id", 
    "show"
  ], 
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "must": {
            "query_string": {
              "query": "安阳", 
              "default_field": "key", 
              "minimum_should_match": "99%"
            }
          }, 
          "filter": [
            {
              "term": {
                "is_show": 1
              }
            }
          ], 
          "must_not": {
            "multi_match": {
              "query": "看不见", 
              "fields": [
                "key", 
                "tags"
              ]
            }
          }
        }
      }, 
      "functions": [
        {
          "script_score": {
            "script": {
              "source": "comma", 
              "lang": "payloadscore", 
              "params": {
                "terms": "安阳", 
                "show_pr_min": 0, 
                "show_pr_max": 72000, 
                "es_score_rate": 0.6, 
                "self_score_rate": 0.4
              }
            }
          }
        }
      ], 
      "boost_mode": "replace"
    }
  }, 
  "highlight": {
    "fields": {
      "display_title": { }
    }, 
    "require_field_match": false
  }, 
  "from": 0, 
  "size": 100, 
  "sort": {
    "_score": {
      "order": "desc"
    }
  }
}

### dict
GET {{baseUrl}}/gateway/dict?word=科技&mode=0

### 搜索
POST {{baseUrl}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": "id",
  "method": "gateway/Search",
  "params": {
    "query": {
      "function_score": {
        "query": {
          "bool" : {
            "must"   : {
              "multi_match" : {
                "query" : "安阳",
                "fields" : [
                    "name^20",
                    "nickname",
                    "job"
                ],
                "type" : "most_fields",
                "minimum_should_match" : "100%"
              }
            }
          }
        }
      }
    },
    "size": 10,
    "from": 0,
    "sort": []
   }
}
