@baseUrl = http://127.0.0.1:9401

######## http ########

### 分词
POST {{baseUrl}}/v1/api/segment
Content-Type: application/json

{
  "title": "寻梦天宫起征程！空间站建造阶段后续飞行任务标识发布",
  "tags": "中国,空间站,首个,实验舱段"
}

### 返回实例 ###

#{
#  "code": 200,
#  "msg": "ok",
#  "data": null
#}

######## jsonrpc ########

### Ping
GET {{baseUrl}}/ping
Content-Type: application/json

### 分词
POST {{baseUrl}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": "id",
  "method": "segment/Segment",
  "params": {
      "title":"寻梦天宫起征程！空间站建造阶段后续飞行任务标识发布",
      "tags": "中国,空间站,首个,实验舱段"
   }
}

### 批量分词
POST {{baseUrl}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": "id",
  "method": "segment/BatchSegment",
  "params": {
      "list": {
        "1":{
            "title":"寻梦天宫起征程！空间站建造阶段后续飞行任务标识发布",
            "tags": "中国,空间站,首个,实验舱段"
        },
        "2":{
            "title":"寻梦天宫起征程！空间站建造阶段后续飞行任务标识发布",
            "tags": "中国,空间站,首个,实验舱段"
        },
        "3":{
            "title":"寻梦天宫起征程！空间站建造阶段后续飞行任务标识发布",
            "tags": "中国,空间站,首个,实验舱段"
        }
      }
  }
}
