@baseUrl = {{baseUrl}}
@contentType = application/json

### read
GET {{baseUrl}}/v1/dict/synonym?p_page1&p_limit10
Accept: {{contentType}}

### create
POST {{baseUrl}}/v1/dict/synonym
Content-Type: {{contentType}}

{
	"word_ids": "3,2,3",
	"rate": 1.3,
	"project_id": 1
}

### update
PUT {{baseUrl}}/v1/dict/synonym/116
Content-Type: {{contentType}}

{
	"word_ids": "3,2,3",
	"rate": 1.3,
	"project_id": 1
}

### multiple delete
DELETE {{baseUrl}}/v1/dict/synonym
Content-Type: {{contentType}}

{
	"ids": [116]
}
