server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

#把loki当客户端连接
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      #标签，用于后面的查询
      job: varlogs
      __path__: /var/log/*.log
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
     #标签，用于后面的查询
      job: goaway
      __path__: /var/log/goaway/*.log
