{
 "title": "gateway",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(comma_comma_req_total{job=\"comma\", type=\"all\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "response status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "comma_comma_req_total{job=\"comma\", type=\"succeed\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(comma_comma_req_total{job=\"comma\", type=\"fail\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "response duration seconds bucket",
   "type": "timeseries",
   "description": "rsp duration seconds bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "comma_comma_rsp_duration_seconds_bucket{job=\"comma\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"comma\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "query log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"comma\"}"
    }
   ]
  }
 ]
}